---
- name: Deploy Docker application to AKS
  hosts: localhost
  gather_facts: no
  vars:
    aks_resource_group: "rdaksdemo"
    aks_cluster_name: "rdaks"
    kubeconfig_path: "{{ kubeconfig_path }}"

  tasks:
    - name: Ensure kubectl is installed
      local_action:
        module: shell
        cmd: |
          az aks install-cli

    - name: Ensure the necessary directory exists
      local_action:
        module: file
        path: /tmp/your-app
        state: directory

    - name: Clone the Git repository
      local_action:
        module: git
        repo: 'https://github.com/rzayn19/aksngnix.git'
        dest: /tmp/your-app
        version: HEAD

    - name: Set kubectl context
      local_action:
        module: shell
        cmd: |
          az aks get-credentials --resource-group {{ aks_resource_group }} --name {{ aks_cluster_name }} --file {{ kubeconfig_path }}
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Apply Kubernetes manifests
      local_action:
        module: shell
        cmd: |
          kubectl apply -f /tmp/your-app/deployment.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Verify deployment
      local_action:
        module: shell
        cmd: |
          kubectl get deployments
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: deploy_status

    - name: Show deployment status
      debug:
        msg: "{{ deploy_status.stdout }}"
