---
- name: Deploy Docker application to AKS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Ensure kubectl is installed
      shell: |
        az aks install-cli

    - name: Ensure the necessary directory exists
      file:
        path: /tmp/your-app
        state: directory

    - name: Clone the Git repository
      git:
        repo: 'https://github.com/rzayn19/aksngnix.git'
        dest: /tmp/your-app
        version: HEAD
        
    - name: Read deployment definition
      set_fact:
       definition: "{{ lookup('file', '/tmp/your-app/deployment.yml') }}"
       
    - name: Apply Kubernetes manifests
      kubernetes.core.k8s:
      definition: "{{ deployment_definition }}"
      state: present
        
